# If not running interactively, don't do anything
[[ "$-" != *i* ]] && return

# Check color support, and set appropriate TERM
#if [ "$COLORTERM" == "gnome-terminal" ] || [ "$COLORTERM" == "xfce4-terminal" ]; then
#    TERM=xterm-256color
#elif [ "$COLORTERM" == "rxvt-xpm" ]; then
#    TERM=rxvt-256color
#fi

# Bash history settings
shopt -s histappend
shopt -s cmdhist
export HISTFILE=$HOME/.history/bash_history
export HISTSIZE=10000
export HISTCONTROL=ignoreboth
export HISTTIMEFORMAT='%F %T '
export HISTIGNORE='ls:bg:fg:history'


# Add dir_colors
eval `dircolors $HOME/.bash/dir_colors`

# Add user defined dir to PATH
export PATH=$PATH:$HOME/opt/bin:$HOME/.local/bin:/usr/java/latest/bin:
export GOPATH=$HOME/go

# Set the default EDITOR
export EDITOR=vim

# Source bash functions
if [ -f "${HOME}/.bash/bash_functions" ]; then
    source "${HOME}/.bash/bash_functions"
fi

# Source private
if [ -f "${HOME}/.bash/bash_private" ]; then
    source "${HOME}/.bash/bash_private"
fi

# Source git completion functions
if [ -f "${HOME}/.bash/git-completion" ]; then
    source "${HOME}/.bash/git-completion"
fi

# Source git prompt functions
if [ -f "${HOME}/.bash/git-prompt" ]; then
    source "${HOME}/.bash/git-prompt"
    # Set options for the git PS1
    export GIT_PS1_SHOWDIRTYSTATE=1
    export GIT_PS1_SHOWSTASHSTATE=1
    export GIT_PS1_SHOWUNTRACKEDFILES=1
    export GIT_PS1_SHOWCOLORHINTS=1
    export GIT_PS1_SHOWUPSTREAM=1
fi

# Aliases:
alias grep='grep --color=always'
alias sourceme='source ~/.bash_profile'
alias pcat='pygmentize -f terminal256 -O style=monokai -g'
alias cd=cd_func
alias mknote='touch $(date +%Y%m%d).note'
alias scavenge="free && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches' && free"
alias weechat-bitlbee="weechat -d ${HOME}/.weechat-xmpp"

# Special provisioning for ls++ aliasing
alias ls='ls --color=tty'
if command_exists ls++; then
    alias ll='ls++ --potsf'
    alias lt='ls++ --potsf -tr'
    alias la='ls++ --potsf -a'
else
    alias la='ls -lah'
    alias ll='ls -lh'
    alias lt='ls -lhtr'
fi
    

# ANSI Escape codes:
ANSI_WHITE="\[\033[00;37m\]"
ANSI_LTBLU="\[\033[00;34m\]"
ANSI_GREEN="\[\033[00;32m\]"
ANSI_RED="\[\033[00;31m\]"
ANSI_CLR="\[\033[00m\]"

# Bash Prompt:
#PS1="$ANSI_WHITE┌─ $ANSI_LTBLU{ \w }$ANSI_WHITE"'$(parse_git_branch)'"\n$ANSI_WHITE└─ $ANSI_GREEN\u$ANSI_LTBLU@$ANSI_RED\h$ANSI_GREEN->$ANSI_WHITE$ $ANSI_CLR"

PROMPT_COMMAND='__git_ps1 "$ANSI_WHITE┌─ $ANSI_LTBLU{ \w }$ANSI_CLR" "\n$ANSI_WHITE└─ $ANSI_GREEN\u$ANSI_LTBLU@$ANSI_RED\h$ANSI_GREEN->$ANSI_WHITE$ $ANSI_CLR"'
PROMPT_COMMAND="history -a;$PROMPT_COMMAND"
