#! /bin/sh

bspc config border_width        2
bspc config window_gap         12
bspc config top_padding        15

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor DVI-I-2 -d I II III IV
bspc monitor DVI-I-3 -d V VI VII VIII

bspc rule -a crx_nckgahadagoaajjgafhacjanaoiihapd desktop=^7 floating=on

${HOME}/.config/bspwm/panel
