# vim: ft=sh

alias grep='grep --color=always'
alias sourceme='source ~/.bash_profile'
alias pcat='pygmentize -f terminal256 -O style=monokai -g'
alias mknote='touch $(date +%Y%m%d).note'
alias scavenge="free && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches' && free"
alias cidr_sort="sort -n -t . -k 1,1 -k 2,2 -k 3,3 -k 4,4"
alias kc='kubectl'

if [[ -z "$OSX" ]]; then
  alias ls='ls --color=always'
else
  alias ls='ls -G'
fi
alias la='ls -lah'
alias ll='ls -lh'
alias lt='ls -lhtr'
alias ld='ls -lhd */'

# OSX Specific stuff
if [[ -n "$OSX" ]]; then
  alias postgres_start="pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start"
  alias postgres_stop="pg_ctl -D /usr/local/var/postgres stop -s -m fast"
  alias watch='watch '
fi
